version: '2'

volumes:
   mysqldata: ~

services:
    php:
        image: php:7.3-fpm
        build: .
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        ports:
            # On se lit au port 80 local, mais on pourrait aussi en choisir un autre comme par exemple "8080:80"
            - "80:80"

    mysql:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            # Nécessaire
            - MYSQL_ROOT_PASSWORD=test
            # On peut configurer sa BDD et les credentials pour s'y connecter
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=test
        ports:
            # On rend la BDD accessible depuis notre ordinateur pour le débug
            - "3306:3306"
